<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="76" started-at="2014-06-28T12:15:48Z" finished-at="2014-06-28T12:15:48Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="76" started-at="2014-06-28T12:15:48Z" finished-at="2014-06-28T12:15:48Z">
      <class name="src.test.java.com.sirma.itt.javacourse.sumator.SumatorTest">
        <test-method status="FAIL" signature="TestSumatorWithBigIntegers()[pri:0, instance:src.test.java.com.sirma.itt.javacourse.sumator.SumatorTest@133adc]" name="TestSumatorWithBigIntegers" duration-ms="27" started-at="2014-06-28T15:15:48Z" finished-at="2014-06-28T15:15:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Nope]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Nope
	at org.testng.Assert.fail(Assert.java:94)
	at src.test.java.com.sirma.itt.javacourse.sumator.SumatorTest.TestSumatorWithBigIntegers(SumatorTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestSumatorWithBigIntegers -->
        <test-method status="PASS" signature="testSumatorWithIntegers()[pri:0, instance:src.test.java.com.sirma.itt.javacourse.sumator.SumatorTest@133adc]" name="testSumatorWithIntegers" duration-ms="2" started-at="2014-06-28T15:15:48Z" finished-at="2014-06-28T15:15:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSumatorWithIntegers -->
      </class> <!-- src.test.java.com.sirma.itt.javacourse.sumator.SumatorTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
